# Generated by Django 4.2.2 on 2023-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_plot',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
