# Generated by Django 4.2.2 on 2023-06-11 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_movie_file_remove_movie_image_movie_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_title', models.CharField(max_length=150, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
